const COLORS = {
  stone: { normal: "bg-amber-100 text-amber-800 border-amber-300", highlight: "bg-amber-800 text-white border-amber-900" },
  citrus: { normal: "bg-yellow-100 text-yellow-800 border-yellow-300", highlight: "bg-yellow-600 text-white border-yellow-700" },
  berry: { normal: "bg-fuchsia-100 text-fuchsia-800 border-fuchsia-300", highlight: "bg-fuchsia-800 text-white border-fuchsia-900" },
  tropical: { normal: "bg-orange-100 text-orange-800 border-orange-300", highlight: "bg-orange-600 text-white border-orange-700" },
  dried: { normal: "bg-violet-100 text-violet-800 border-violet-300", highlight: "bg-violet-800 text-white border-violet-900" },
  orchard: { normal: "bg-lime-100 text-lime-800 border-lime-300", highlight: "bg-lime-700 text-white border-lime-800" },
  floral: { normal: "bg-pink-100 text-pink-800 border-pink-300", highlight: "bg-pink-700 text-white border-pink-800" },
  sweet: { normal: "bg-yellow-50 text-yellow-700 border-yellow-200", highlight: "bg-yellow-600 text-white border-yellow-700" },
  chocolate: { normal: "bg-amber-200 text-amber-900 border-amber-400", highlight: "bg-amber-800 text-white border-amber-900" },
  nutty: { normal: "bg-amber-50 text-amber-700 border-amber-200", highlight: "bg-amber-700 text-white border-amber-800" },
  spice: { normal: "bg-red-100 text-red-800 border-red-300", highlight: "bg-red-700 text-white border-red-800" },
  tea: { normal: "bg-emerald-100 text-emerald-800 border-emerald-300", highlight: "bg-emerald-700 text-white border-emerald-800" },
  wine: { normal: "bg-rose-100 text-rose-800 border-rose-300", highlight: "bg-rose-700 text-white border-rose-800" },
  herbal: { normal: "bg-green-100 text-green-800 border-green-300", highlight: "bg-green-700 text-white border-green-800" },
  baked: { normal: "bg-orange-50 text-orange-700 border-orange-200", highlight: "bg-orange-600 text-white border-orange-700" },
  creamy: { normal: "bg-slate-100 text-slate-700 border-slate-300", highlight: "bg-slate-700 text-white border-slate-800" },
  other: { normal: "bg-gray-100 text-gray-700 border-gray-300", highlight: "bg-gray-700 text-white border-gray-800" },
} as const;

// Category to notes mapping for semantic search
export const CATEGORY_TO_NOTES: Record<string, string[]> = {
  stone: ["peach", "apricot", "nectarine", "plum", "cherry", "black cherry", "stone fruit", "prune", "persimmon"],
  citrus: ["citrus", "orange", "blood orange", "tangerine", "mandarin", "lemon", "lime", "grapefruit", "bergamot", "yuzu"],
  berry: ["berry", "berries", "red berries", "dark berries", "blueberry", "raspberry", "strawberry", "blackberry", "blackcurrant", "redcurrant", "cranberry", "gooseberry"],
  tropical: ["tropical", "mango", "pineapple", "papaya", "passion fruit", "guava", "lychee", "coconut", "banana", "kiwi"],
  dried: ["raisin", "date", "fig", "dried fruits", "fruitcake", "tamarind"],
  orchard: ["apple", "green apple", "pear", "grape", "melon", "watermelon", "pomegranate"],
  floral: ["floral", "jasmine", "rose", "lavender", "violet", "hibiscus", "honeysuckle", "geranium", "chamomile"],
  sweet: ["honey", "caramel", "toffee", "fudge", "maple", "brown sugar", "molasses", "panela", "candy"],
  chocolate: ["chocolate", "dark chocolate", "milk chocolate", "cocoa", "cacao"],
  nutty: ["nutty", "almond", "hazelnut", "walnut", "pistachio", "macadamia", "pecan", "marzipan", "praline"],
  spice: ["cinnamon", "cardamom", "ginger", "baking spice"],
  tea: ["tea", "black tea", "green tea", "oolong", "darjeeling"],
  wine: ["wine", "red wine", "brandy", "rum", "jammy"],
  herbal: ["herbal", "lemongrass", "verbena", "eucalyptus", "tobacco"],
  baked: ["brioche", "biscuit", "grains", "malt"],
  creamy: ["cream", "custard", "vanilla", "butter"],
  other: ["fresh", "crisp", "bright", "juicy", "complex", "fermented", "wild", "yeasty", "boozy", "winey"],
};

// Flat list of all notes for LLM prompts
export const ALL_NOTES = Object.values(CATEGORY_TO_NOTES).flat();

// Common coffee processes
export const ALL_PROCESSES = [
  "washed", "natural", "honey", "anaerobic", "carbonic maceration",
  "double fermentation", "extended fermentation", "thermal shock",
  "wet hulled", "semi-washed", "pulped natural",
];

type ColorConfig = typeof COLORS[keyof typeof COLORS];

const NOTES: Record<string, { emoji: string; color: ColorConfig }> = {
  // Stone fruits
  peach: { emoji: "🍑", color: COLORS.stone },
  peaches: { emoji: "🍑", color: COLORS.stone },
  "yellow peach": { emoji: "🍑", color: COLORS.stone },
  apricot: { emoji: "🍑", color: COLORS.stone },
  "apricot jam": { emoji: "🍑", color: COLORS.stone },
  "apricot butter": { emoji: "🍑", color: COLORS.stone },
  "dried apricot": { emoji: "🍑", color: COLORS.stone },
  nectarine: { emoji: "🍑", color: COLORS.stone },
  "white nectarine": { emoji: "🍑", color: COLORS.stone },
  plum: { emoji: "🍑", color: COLORS.stone },
  "red plum": { emoji: "🍑", color: COLORS.stone },
  "yellow plum": { emoji: "🍑", color: COLORS.stone },
  "dried plum": { emoji: "🍑", color: COLORS.stone },
  "mirabelle plum": { emoji: "🍑", color: COLORS.stone },
  mirabelle: { emoji: "🍑", color: COLORS.stone },
  cherry: { emoji: "🍒", color: COLORS.stone },
  "black cherry": { emoji: "🍒", color: COLORS.stone },
  "wild cherry": { emoji: "🍒", color: COLORS.stone },
  "red cherries": { emoji: "🍒", color: COLORS.stone },
  "cherry candy": { emoji: "🍒", color: COLORS.stone },
  "cherry liqueur": { emoji: "🍒", color: COLORS.stone },
  "cherry blossom": { emoji: "🌸", color: COLORS.stone },
  "glacé cherry": { emoji: "🍒", color: COLORS.stone },
  "stone fruit": { emoji: "🍑", color: COLORS.stone },
  stonefruit: { emoji: "🍑", color: COLORS.stone },
  "red stone fruit": { emoji: "🍑", color: COLORS.stone },
  prune: { emoji: "🍑", color: COLORS.stone },
  persimmon: { emoji: "🍑", color: COLORS.stone },

  // Citrus
  citrus: { emoji: "🍊", color: COLORS.citrus },
  orange: { emoji: "🍊", color: COLORS.citrus },
  "blood orange": { emoji: "🍊", color: COLORS.citrus },
  "orange zest": { emoji: "🍊", color: COLORS.citrus },
  "orange blossom": { emoji: "🌸", color: COLORS.citrus },
  "orange marmalade": { emoji: "🍊", color: COLORS.citrus },
  "orange candy": { emoji: "🍊", color: COLORS.citrus },
  "orange liqueur": { emoji: "🍊", color: COLORS.citrus },
  "orange sherbet": { emoji: "🍊", color: COLORS.citrus },
  orangette: { emoji: "🍊", color: COLORS.citrus },
  "candied orange": { emoji: "🍊", color: COLORS.citrus },
  tangerine: { emoji: "🍊", color: COLORS.citrus },
  mandarin: { emoji: "🍊", color: COLORS.citrus },
  mandarine: { emoji: "🍊", color: COLORS.citrus },
  "mandarin peel": { emoji: "🍊", color: COLORS.citrus },
  "mandarin zest": { emoji: "🍊", color: COLORS.citrus },
  clementine: { emoji: "🍊", color: COLORS.citrus },
  satsuma: { emoji: "🍊", color: COLORS.citrus },
  lemon: { emoji: "🍋", color: COLORS.citrus },
  "meyer lemon": { emoji: "🍋", color: COLORS.citrus },
  "candied lemon": { emoji: "🍋", color: COLORS.citrus },
  "lemon candy": { emoji: "🍋", color: COLORS.citrus },
  "lemon nougat": { emoji: "🍋", color: COLORS.citrus },
  lemonade: { emoji: "🍋", color: COLORS.citrus },
  "pink lemonade": { emoji: "🍋", color: COLORS.citrus },
  lime: { emoji: "🍋", color: COLORS.citrus },
  "key lime": { emoji: "🍋", color: COLORS.citrus },
  "kaffir lime": { emoji: "🍋", color: COLORS.citrus },
  "lime zest": { emoji: "🍋", color: COLORS.citrus },
  grapefruit: { emoji: "🍊", color: COLORS.citrus },
  "red grapefruit": { emoji: "🍊", color: COLORS.citrus },
  pomelo: { emoji: "🍊", color: COLORS.citrus },
  bergamot: { emoji: "🍋", color: COLORS.citrus },
  "bergamot tea": { emoji: "🍋", color: COLORS.citrus },
  yuzu: { emoji: "🍋", color: COLORS.citrus },
  citron: { emoji: "🍋", color: COLORS.citrus },
  "candied citrus": { emoji: "🍊", color: COLORS.citrus },
  marmalade: { emoji: "🍊", color: COLORS.citrus },

  // Berry
  berry: { emoji: "🫐", color: COLORS.berry },
  berries: { emoji: "🫐", color: COLORS.berry },
  "red berries": { emoji: "🍓", color: COLORS.berry },
  "red berry": { emoji: "🍓", color: COLORS.berry },
  "dark berries": { emoji: "🫐", color: COLORS.berry },
  "wild berries": { emoji: "🫐", color: COLORS.berry },
  "berry compote": { emoji: "🫐", color: COLORS.berry },
  blueberry: { emoji: "🫐", color: COLORS.berry },
  blueberries: { emoji: "🫐", color: COLORS.berry },
  "blueberry muffin": { emoji: "🫐", color: COLORS.berry },
  raspberry: { emoji: "🍓", color: COLORS.berry },
  raspberries: { emoji: "🍓", color: COLORS.berry },
  strawberry: { emoji: "🍓", color: COLORS.berry },
  "strawberry jam": { emoji: "🍓", color: COLORS.berry },
  "strawberry juice": { emoji: "🍓", color: COLORS.berry },
  "strawberry flower": { emoji: "🍓", color: COLORS.berry },
  blackberry: { emoji: "🫐", color: COLORS.berry },
  blackberries: { emoji: "🫐", color: COLORS.berry },
  "blackberry jam": { emoji: "🫐", color: COLORS.berry },
  blackcurrant: { emoji: "🫐", color: COLORS.berry },
  "black currant": { emoji: "🫐", color: COLORS.berry },
  redcurrant: { emoji: "🍓", color: COLORS.berry },
  "red currant": { emoji: "🍓", color: COLORS.berry },
  "red currants": { emoji: "🍓", color: COLORS.berry },
  cranberry: { emoji: "🍓", color: COLORS.berry },
  cranberries: { emoji: "🍓", color: COLORS.berry },
  gooseberry: { emoji: "🫐", color: COLORS.berry },
  tayberry: { emoji: "🫐", color: COLORS.berry },
  "red fruits": { emoji: "🍓", color: COLORS.berry },
  "dark fruits": { emoji: "🫐", color: COLORS.berry },

  // Tropical
  tropical: { emoji: "🥭", color: COLORS.tropical },
  "tropical fruit": { emoji: "🥭", color: COLORS.tropical },
  "tropical fruits": { emoji: "🥭", color: COLORS.tropical },
  mango: { emoji: "🥭", color: COLORS.tropical },
  pineapple: { emoji: "🍍", color: COLORS.tropical },
  "caramelized pineapple": { emoji: "🍍", color: COLORS.tropical },
  "dried pineapple": { emoji: "🍍", color: COLORS.tropical },
  papaya: { emoji: "🥭", color: COLORS.tropical },
  "passion fruit": { emoji: "🥭", color: COLORS.tropical },
  guava: { emoji: "🥭", color: COLORS.tropical },
  "pink guava": { emoji: "🥭", color: COLORS.tropical },
  lychee: { emoji: "🥭", color: COLORS.tropical },
  coconut: { emoji: "🥥", color: COLORS.tropical },
  banana: { emoji: "🍌", color: COLORS.tropical },
  "banana bread": { emoji: "🍌", color: COLORS.tropical },
  kiwi: { emoji: "🥝", color: COLORS.tropical },
  "golden kiwi": { emoji: "🥝", color: COLORS.tropical },
  "star fruit": { emoji: "⭐", color: COLORS.tropical },
  "dragon fruit": { emoji: "🥭", color: COLORS.tropical },
  "yellow fruit": { emoji: "🥭", color: COLORS.tropical },
  "yellow fruits": { emoji: "🥭", color: COLORS.tropical },
  "yellow fruit candy": { emoji: "🥭", color: COLORS.tropical },

  // Dried fruits
  raisin: { emoji: "🍇", color: COLORS.dried },
  raisins: { emoji: "🍇", color: COLORS.dried },
  "rum raisin": { emoji: "🍇", color: COLORS.dried },
  date: { emoji: "🍇", color: COLORS.dried },
  dates: { emoji: "🍇", color: COLORS.dried },
  "date syrup": { emoji: "🍇", color: COLORS.dried },
  "date molasses": { emoji: "🍇", color: COLORS.dried },
  fig: { emoji: "🍇", color: COLORS.dried },
  figs: { emoji: "🍇", color: COLORS.dried },
  "dried fruits": { emoji: "🍇", color: COLORS.dried },
  fruitcake: { emoji: "🍇", color: COLORS.dried },
  "stewed fruit": { emoji: "🍇", color: COLORS.dried },
  "rich fruit": { emoji: "🍇", color: COLORS.dried },
  tamarind: { emoji: "🍇", color: COLORS.dried },

  // Orchard
  apple: { emoji: "🍎", color: COLORS.orchard },
  "green apple": { emoji: "🍏", color: COLORS.orchard },
  "red apple": { emoji: "🍎", color: COLORS.orchard },
  "gala apple": { emoji: "🍎", color: COLORS.orchard },
  "elstar apple": { emoji: "🍎", color: COLORS.orchard },
  "baked apple": { emoji: "🍎", color: COLORS.orchard },
  "cooked apple": { emoji: "🍎", color: COLORS.orchard },
  "candied apple": { emoji: "🍎", color: COLORS.orchard },
  "candy apple": { emoji: "🍎", color: COLORS.orchard },
  pear: { emoji: "🍐", color: COLORS.orchard },
  "baked pear": { emoji: "🍐", color: COLORS.orchard },
  "poached pear": { emoji: "🍐", color: COLORS.orchard },
  grape: { emoji: "🍇", color: COLORS.orchard },
  grapes: { emoji: "🍇", color: COLORS.orchard },
  "green grapes": { emoji: "🍇", color: COLORS.orchard },
  "purple grape": { emoji: "🍇", color: COLORS.orchard },
  melon: { emoji: "🍈", color: COLORS.orchard },
  "honeydew melon": { emoji: "🍈", color: COLORS.orchard },
  watermelon: { emoji: "🍉", color: COLORS.orchard },
  pomegranate: { emoji: "🍎", color: COLORS.orchard },
  "pomegranate molasses": { emoji: "🍎", color: COLORS.orchard },
  "ripe fruit": { emoji: "🍎", color: COLORS.orchard },
  agraz: { emoji: "🍇", color: COLORS.orchard },

  // Floral
  floral: { emoji: "🌸", color: COLORS.floral },
  florals: { emoji: "🌸", color: COLORS.floral },
  flowers: { emoji: "🌸", color: COLORS.floral },
  "white floral": { emoji: "🌸", color: COLORS.floral },
  "white florals": { emoji: "🌸", color: COLORS.floral },
  "white flowers": { emoji: "🌸", color: COLORS.floral },
  "red florals": { emoji: "🌺", color: COLORS.floral },
  jasmine: { emoji: "🌸", color: COLORS.floral },
  "jasmine florals": { emoji: "🌸", color: COLORS.floral },
  rose: { emoji: "🌹", color: COLORS.floral },
  "rose water": { emoji: "🌹", color: COLORS.floral },
  rosehip: { emoji: "🌹", color: COLORS.floral },
  lavender: { emoji: "💜", color: COLORS.floral },
  violet: { emoji: "💜", color: COLORS.floral },
  violets: { emoji: "💜", color: COLORS.floral },
  hibiscus: { emoji: "🌺", color: COLORS.floral },
  honeysuckle: { emoji: "🌸", color: COLORS.floral },
  geranium: { emoji: "🌸", color: COLORS.floral },
  magnolia: { emoji: "🌸", color: COLORS.floral },
  chamomile: { emoji: "🌼", color: COLORS.floral },
  osmanthus: { emoji: "🌸", color: COLORS.floral },
  "plum blossom": { emoji: "🌸", color: COLORS.floral },
  "apple blossom": { emoji: "🌸", color: COLORS.floral },
  sakura: { emoji: "🌸", color: COLORS.floral },

  // Sweet
  honey: { emoji: "🍯", color: COLORS.sweet },
  honeycomb: { emoji: "🍯", color: COLORS.sweet },
  caramel: { emoji: "🍬", color: COLORS.sweet },
  "light caramel": { emoji: "🍬", color: COLORS.sweet },
  "caramelized sugar": { emoji: "🍬", color: COLORS.sweet },
  toffee: { emoji: "🍬", color: COLORS.sweet },
  "sticky toffee pudding": { emoji: "🍬", color: COLORS.sweet },
  fudge: { emoji: "🍬", color: COLORS.sweet },
  "white fudge": { emoji: "🍬", color: COLORS.sweet },
  maple: { emoji: "🍁", color: COLORS.sweet },
  "maple syrup": { emoji: "🍁", color: COLORS.sweet },
  "brown sugar": { emoji: "🍬", color: COLORS.sweet },
  "cane sugar": { emoji: "🍬", color: COLORS.sweet },
  "sugar cane": { emoji: "🍬", color: COLORS.sweet },
  "white sugar": { emoji: "🍬", color: COLORS.sweet },
  molasses: { emoji: "🍯", color: COLORS.sweet },
  "golden syrup": { emoji: "🍯", color: COLORS.sweet },
  panela: { emoji: "🍬", color: COLORS.sweet },
  panella: { emoji: "🍬", color: COLORS.sweet },
  candy: { emoji: "🍬", color: COLORS.sweet },
  bubblegum: { emoji: "🍬", color: COLORS.sweet },
  "jelly tot": { emoji: "🍬", color: COLORS.sweet },
  "pink fruitella": { emoji: "🍬", color: COLORS.sweet },
  "tutti-frutti": { emoji: "🍬", color: COLORS.sweet },
  "turkish delight": { emoji: "🍬", color: COLORS.sweet },
  caramac: { emoji: "🍬", color: COLORS.sweet },
  "cream soda": { emoji: "🥤", color: COLORS.sweet },
  cola: { emoji: "🥤", color: COLORS.sweet },
  "root beer": { emoji: "🥤", color: COLORS.sweet },
  licorice: { emoji: "🍬", color: COLORS.sweet },

  // Chocolate
  chocolate: { emoji: "🍫", color: COLORS.chocolate },
  "dark chocolate": { emoji: "🍫", color: COLORS.chocolate },
  "milk chocolate": { emoji: "🍫", color: COLORS.chocolate },
  "white chocolate": { emoji: "🍫", color: COLORS.chocolate },
  "baker's chocolate": { emoji: "🍫", color: COLORS.chocolate },
  "chocolate liqueur": { emoji: "🍫", color: COLORS.chocolate },
  "chocolate mousse": { emoji: "🍫", color: COLORS.chocolate },
  cocoa: { emoji: "🍫", color: COLORS.chocolate },
  "cocoa bean": { emoji: "🍫", color: COLORS.chocolate },
  "cocoa butter": { emoji: "🍫", color: COLORS.chocolate },
  cacao: { emoji: "🍫", color: COLORS.chocolate },
  cacaonibs: { emoji: "🍫", color: COLORS.chocolate },

  // Nutty
  nuts: { emoji: "🥜", color: COLORS.nutty },
  nutty: { emoji: "🥜", color: COLORS.nutty },
  almond: { emoji: "🥜", color: COLORS.nutty },
  almonds: { emoji: "🥜", color: COLORS.nutty },
  hazelnut: { emoji: "🌰", color: COLORS.nutty },
  hazelnuts: { emoji: "🌰", color: COLORS.nutty },
  "hazelnut praline": { emoji: "🌰", color: COLORS.nutty },
  walnut: { emoji: "🥜", color: COLORS.nutty },
  "brazil nut": { emoji: "🥜", color: COLORS.nutty },
  pistachio: { emoji: "🥜", color: COLORS.nutty },
  macadamia: { emoji: "🥜", color: COLORS.nutty },
  pecan: { emoji: "🥜", color: COLORS.nutty },
  "pecan pie": { emoji: "🥜", color: COLORS.nutty },
  marzipan: { emoji: "🥜", color: COLORS.nutty },
  praline: { emoji: "🌰", color: COLORS.nutty },
  praliné: { emoji: "🌰", color: COLORS.nutty },
  nougat: { emoji: "🥜", color: COLORS.nutty },
  amaretto: { emoji: "🥜", color: COLORS.nutty },
  "peanut butter": { emoji: "🥜", color: COLORS.nutty },

  // Spice
  spices: { emoji: "🌶️", color: COLORS.spice },
  spicy: { emoji: "🌶️", color: COLORS.spice },
  cinnamon: { emoji: "🌶️", color: COLORS.spice },
  cardamom: { emoji: "🌶️", color: COLORS.spice },
  cardamon: { emoji: "🌶️", color: COLORS.spice },
  ginger: { emoji: "🫚", color: COLORS.spice },
  gingerbread: { emoji: "🫚", color: COLORS.spice },
  "baking spice": { emoji: "🌶️", color: COLORS.spice },
  "brown spice": { emoji: "🌶️", color: COLORS.spice },
  "pink pepper": { emoji: "🌶️", color: COLORS.spice },
  galangal: { emoji: "🫚", color: COLORS.spice },

  // Tea
  tea: { emoji: "🍵", color: COLORS.tea },
  "black tea": { emoji: "🍵", color: COLORS.tea },
  "green tea": { emoji: "🍵", color: COLORS.tea },
  "white tea": { emoji: "🍵", color: COLORS.tea },
  "oolong tea": { emoji: "🍵", color: COLORS.tea },
  darjeeling: { emoji: "🍵", color: COLORS.tea },
  hojicha: { emoji: "🍵", color: COLORS.tea },
  rooibos: { emoji: "🍵", color: COLORS.tea },

  // Wine
  wine: { emoji: "🍷", color: COLORS.wine },
  "red wine": { emoji: "🍷", color: COLORS.wine },
  "white wine": { emoji: "🍷", color: COLORS.wine },
  brandy: { emoji: "🥃", color: COLORS.wine },
  rum: { emoji: "🥃", color: COLORS.wine },
  hops: { emoji: "🍺", color: COLORS.wine },
  jammy: { emoji: "🍷", color: COLORS.wine },

  // Herbal
  herbal: { emoji: "🌿", color: COLORS.herbal },
  vegetal: { emoji: "🌿", color: COLORS.herbal },
  lemongrass: { emoji: "🌿", color: COLORS.herbal },
  "lemon verbena": { emoji: "🌿", color: COLORS.herbal },
  verbena: { emoji: "🌿", color: COLORS.herbal },
  eucalyptus: { emoji: "🌿", color: COLORS.herbal },
  tobacco: { emoji: "🍂", color: COLORS.herbal },
  sunflower: { emoji: "🌻", color: COLORS.herbal },

  // Baked
  brioche: { emoji: "🥐", color: COLORS.baked },
  "vanilla brioche": { emoji: "🥐", color: COLORS.baked },
  biscuit: { emoji: "🍪", color: COLORS.baked },
  "rich tea biscuit": { emoji: "🍪", color: COLORS.baked },
  canelé: { emoji: "🥐", color: COLORS.baked },
  "battenberg cake": { emoji: "🍰", color: COLORS.baked },
  grains: { emoji: "🌾", color: COLORS.baked },
  "roasted grains": { emoji: "🌾", color: COLORS.baked },
  malt: { emoji: "🌾", color: COLORS.baked },

  // Creamy
  cream: { emoji: "🧈", color: COLORS.creamy },
  creamy: { emoji: "🧈", color: COLORS.creamy },
  custard: { emoji: "🍮", color: COLORS.creamy },
  "vanilla custard": { emoji: "🍮", color: COLORS.creamy },
  "creme brulee": { emoji: "🍮", color: COLORS.creamy },
  "crème brûlée": { emoji: "🍮", color: COLORS.creamy },
  vanilla: { emoji: "🍦", color: COLORS.creamy },
  butter: { emoji: "🧈", color: COLORS.creamy },
  "beurre noisette": { emoji: "🧈", color: COLORS.creamy },

  // Other
  fresh: { emoji: "✨", color: COLORS.other },
  crisp: { emoji: "✨", color: COLORS.other },
  bright: { emoji: "✨", color: COLORS.other },
  juicy: { emoji: "💧", color: COLORS.other },
  complex: { emoji: "✨", color: COLORS.other },
};

const DEFAULT_NOTE = { emoji: "✨", color: COLORS.other };

export function getTastingNoteInfo(note: string): { emoji: string; color: ColorConfig } {
  return NOTES[note.toLowerCase().trim()] ?? DEFAULT_NOTE;
}
